export const START_TEST_LONG_TASK = 'START_TEST_LONG_TASK'
export const PROGRESS_TEST_LONG_TASK = 'PROGRESS_TEST_LONG_TASK'
export const FINISH_TEST_LONG_TASK = 'FINISH_TEST_LONG_TASK'
export const ABORT_TEST_LONG_TASK = 'ABORT_TEST_LONG_TASK'