version: '3.0'
services:
  api:
    build: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    working_dir: /app
    command: ['yarn', 'run', 'production']
    restart: always
    volumes:
      - /srv/cailab-database-v2/logs:/app/logs

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    links:
      - api
    depends_on:
      - api
    command: ['nginx', '-g', 'daemon off;']

    
