version: '3.0'
services:
  api:
    container_name: webexe-api
    build: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    working_dir: /app
    command: ['yarn', 'run', 'production']
    restart: always
    volumes:
      - /srv/cailab-database-v2/logs:/app/logs
    network_mode: bridge

  frontend:
    container_name: webexe-frontend
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    links:
      - api
    depends_on:
      - api
    command: ['nginx', '-g', 'daemon off;']
    network_mode: bridge

    
