
export const TEST_CONNECTION = 'TEST_CONNECTION';
export const FILE_UPLOADING_FAILED = 'FILE_UPLOADING_FAILED';
export const SHOW_CONNECTED = 'SHOW_CONNECTED';
export const SHOW_DISCONNECTED = 'SHOW_DISCONNECTED';

export const GET_AVAILABLE_TASKS = 'GET_AVAILABLE_TASKS';
export const SET_AVAILABLE_TASKS = 'SET_AVAILABLE_TASKS';

export const GET_CURENT_USER = 'GET_CURENT_USER';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const LOG_OUT = 'LOG_OUT';