
export const TEST_CONNECTION = 'TEST_CONNECTION';
export const FILE_UPLOADING_FAILED = 'FILE_UPLOADING_FAILED';
export const SHOW_CONNECTED = 'SHOW_CONNECTED';
export const SHOW_DISCONNECTED = 'SHOW_DISCONNECTED';
